
version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: smart-clinic-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartclinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-clinic-api
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smartclinic
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
